# PrivX instance variables.

HOSTNAME = "example.privx.com"
HOSTPORT = 443

CA_CERT = """
ADD PRIVX CA CERT HERE
"""

OAUTH_CLIENT_ID = "privx-external"
OAUTH_CLIENT_SECRET = "ADD OAUTH CLIENT SECRET HERE"

API_CLIENT_ID = "ADD API CLIENT ID HERE"
API_CLIENT_SECRET = "ADD API CLIENT SECRET HERE"
